### ISSUE TITLE
update the preview at Astro.build

### ISSUE THREAD

**Issue by tomByrer** [rodneylab/astro-blog-markdown#1]
![image](https://github.com/rodneylab/astro-blog-markdown/assets/1308419/8d8c8fc5-133c-4692-9839-37ea1b5b9311)

I was in bit surprised when the preview in their hero-image didn't match your new version.  :)

Thanks for open-sourcing it!

**Comment by rodneylab** [comment]
Thanks @tomByrer. I&rsquo;ll take a look!

**Comment by tomByrer** [comment]
Perhaps I'm confused; I guess your current blog is using SevlteKit, not Astro?

**Comment by rodneylab** [comment]
I see, this repo is for an Astro blog template, not my blog site.
